spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/huangwei-github/spring-cloud-tutorial
          search-paths: springcloud-itoken/itoken-config/config
  boot:
    admin:
      client:
        url: http://localhost:9004
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka    #defaultZone,写成default-zone可能会出错

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
