spring:
  application:
    name: itoken-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/huangwei-github/spring-cloud-tutorial
          search-paths: config
          username:
          password:
  boot:
    admin:
      client:
        url: http://localhost:9004
  zipkin:
    base-url: http://localhost:9411

server:
  port: 9002

eureka:
  client:
    service-url:
      default-zone: http://localhost:9001/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
