spring:
  application:
    name: springcloud-admin-cloud
  boot:
    admin:
      client:
        url: http://localhost:8769
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8770

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
