spring:
  application:
    name: springcloud-zuul

server:
  port: 8769

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: springcloud-ribbon
    api-b:
      path: /api/b/**
      serviceId: springcloud-feign
