spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://localhost:9004
  zipkin:
    base-url:
      default-zone: http://localhost:9411

server:
  port: 9003

eureka:
  client:
    service-url:
      default-zone: http://localhost:9001/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info