spring:
  application:
    name: itoken-admin
  zipkin:
    base-url:
      default-zone: http://localhost:9411

server:
  port: 9004

eureka:
  client:
    service-url:
      default-zone: http://localhost:9001/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info