spring:
  application:
    name: springcloud-admin-server
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8769

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

