spring:
  application:
    name: springcloud-feign
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8765

eureka:
  client:
    service-url:
      deafult-zone: http://localhost:8761/eureka

feign:
  hystrix:
    enabled: true